//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelprocessing.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child_Guest
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public long PhoneNumber { get; set; }
        public int ParentID { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
