//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotelprocessing.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelNumber
    {
        public int Id { get; set; }
        public string Comfortable { get; set; }
        public byte BedCount { get; set; }
        public bool IsEmpty { get; set; }
        public decimal Price { get; set; }
        public short RoomIndex { get; set; }
        public short FloorIndex { get; set; }
        public int HotelID { get; set; }
        public string Furniture { get; set; }
        public Nullable<int> GuestID { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual HotelInfo HotelInfo { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
